### ISSUE TITLE
Encoder-decoder channel sizes

### ISSUE THREAD

**Issue by shkarupa-alex** [poppinace/fade#1]
As far as i understand current implementation does not supports encoder/decoder feature fusion when channel sizes are different.
Was it done on some purpose?

The most common case in encoder-decoder architectures is to have different channel sizes.
Did you made some experiments about it?

**Comment by poppinace** [comment]
Yes, our implementation requires equal channel numbers of encoder and decoder features. This requirement must be met to use the semi-shift conv. In our experiments, we address the mismatched issue with 1x1 convolution.

**Comment by teleppo** [comment]
Sorry. I just saw your message. Semi-shift conv is applicable whether the number of channels is equal or unequal between the high-res and the low-res feature. Please refer to Fig. 5 and Eq. (1)-(3) in the paper.

The current code only supports equal-channel features because of the gating mechanism. For unequal channels, you can simply use a linear layer to match the channels. For example, 'Aligner' is provided in L 30-42 in FADE_L2H.py, which can be used to modify the 'FADE' class in L 111-125.
